### PR TITLE
Get main branch up to date

### PR DESCRIPTION
**Pull request by Caden64**
# Get main branch up to date
---

It's more clear where the most up to date information is if its on the main branch

another solution may be to add documentation for the most up to date branch.

### CODE REVIEW

**Comment by ddowy** [comment]
I agree with you, I am just trying to use git in the most efficient way and stay organized. How should I implement this while still keeping different parts of development in their own branch?

**Comment by ddowy** [comment]
For the home page edits branch, I am going to merge with main. But for image-upload, that is going to be an extensive project, do you think I should periodically update main, or should I wait until image upload is finish and merge it all at once?

**Comment by Caden64** [comment]
I think we should have an unstable & stable dev branch where breaking changes go into unstable at first and non breaking changes go into the stable dev branch labeled like dev-stable / dev-unstable. we makes these changes using github actions using tools such as [merge-branch](https://github.com/marketplace/actions/merge-branch)

**Comment by Caden64** [comment]
We should have staging development branch's along with feature branches we always merge with dev branches and wait until it's ready for main branches

**Comment by ddowy** [comment]
Okay so like this, we keep main, main is what anyone can clone and that is our stable branch. Then we have a dev branch for any updates we are working on, or multiple branches for different things we are working on.

**Comment by Caden64** [comment]
Yes

**Comment by ddowy** [comment]
This is similar to what we got going on already, but I will make sure to always keep main as stable as possible.

**Comment by cidit** [comment]
stuff's happening over here huh

**Comment by ddowy** [comment]
Getting the ball moving

**Pull request closed without merging**
